version: '3.6'
services:
  kafka:
    image: quay.io/parkhubprime/ph-confluent-kafka:4.1.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9999:9999
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: quay.io/parkhubprime/ph-confluent-zookeeper:4.1.0
    hostname: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_PORT: 2888
      ZOOKEEPER_ELECTION_PORT: 3888
